name: Workflow to be used to cleanup AWS resources

on:
    workflow_dispatch:
    push:

permissions:
    id-token: write

jobs:
    aws-cleanup:
        runs-on: ubuntu-latest
        steps:
            - name: AWS Authentication
              uses: aws-actions/configure-aws-credentials@v4
              with:
                role-to-assume: arn:aws:iam::092376285579:oidc-provider/token.actions.githubusercontent.com
                aws-region: us-east-1
